//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аптечный_склад
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationContent
    {
        public int MedicineCode { get; set; }
        public int ApplicationCode { get; set; }
        public int MedicineQuantity { get; set; }

        public double MedicineTotalCost
        {
            get
            {
                return Medicine.MedicinePrice.Price * MedicineQuantity;
            }
        }
        public virtual Application Application { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
