//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аптечный_склад
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryOperations
    {
        public int OperationCode { get; set; }
        public int UserCode { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public string Details { get; set; }
    
        public virtual User User { get; set; }
    }
}
