//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аптечный_склад
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pharmaceutical_WarehouseEntities : DbContext
    {
        public Pharmaceutical_WarehouseEntities()
            : base("name=Pharmaceutical_WarehouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveSubstance> ActiveSubstance { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<ApplicationStatus> ApplicationStatus { get; set; }
        public virtual DbSet<HistoryOperations> HistoryOperations { get; set; }
        public virtual DbSet<Manufacturer> Manufacturer { get; set; }
        public virtual DbSet<Medicine> Medicine { get; set; }
        public virtual DbSet<MedicineCategory> MedicineCategory { get; set; }
        public virtual DbSet<MedicinePhoto> MedicinePhoto { get; set; }
        public virtual DbSet<MedicineSupply> MedicineSupply { get; set; }
        public virtual DbSet<Pharmacy> Pharmacy { get; set; }
        public virtual DbSet<PharmacyManager> PharmacyManager { get; set; }
        public virtual DbSet<PharmacySupply> PharmacySupply { get; set; }
        public virtual DbSet<ReleaseForm> ReleaseForm { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<ApplicationContent> ApplicationContent { get; set; }
        public virtual DbSet<PharmacySupplyContent> PharmacySupplyContent { get; set; }
        public virtual DbSet<SupplyContent> SupplyContent { get; set; }
        public virtual DbSet<MedicinePrice> MedicinePrice { get; set; }
        public virtual DbSet<MedicineQuantitiy> MedicineQuantitiy { get; set; }
    }
}
