//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Аптечный_склад
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pharmacy()
        {
            this.Application = new HashSet<Application>();
            this.PharmacySupply = new HashSet<PharmacySupply>();
            this.User = new HashSet<User>();
        }
    
        public int PharmacyCode { get; set; }
        public string Title { get; set; }
        public string PharmacistName { get; set; }
        public string PharmacistPhone { get; set; }
        public string Address { get; set; }
        public string DisplayDocumentCode { get; set; }
        public string PharmacistNameDoc
        {
            get
            {
                string[] words = PharmacistName.Split(' ');
                string lastname = words[0];
                string firstname = words[1];
                string patronymic = words[2];
                return $"{lastname} {firstname[0]}. {patronymic[0]}.";
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PharmacySupply> PharmacySupply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
